const commonArray = [
  "irresponsible",
  "uninviting",
  "unapproachable",
  "disorganized",
  "not flexible",
  "refuse",
  "impolite",
  "lazy",
  "horrible",
  "uncooperative",
  "inadequate",
  "ignorant",
  "horrific",
  "careless",
  "empty",
  "stench",
  "stink",
  "inattentive",
  "disrespectful",
  "offensive",
  "unresponsive",
  "unwelcoming",
  "slow",
  "arrogant",
  "not professional",
  "rude",
  "inefficient",
  "off putting",
  "nobody",
  "unfriendly",
  "unprofessional",
  "unorganised",
  "awful",
  "gloomy",
  "reek",
  "ignoring",
  "unsympathetic",
  "dirty",
  "discomfort",
  "staff behavior",
  "terrible",
  "smelling",
  "offensive",
  "dull",
  "horrible hospitality",
  "lousy",
  "negligent",
  "smelly",
  "dirty",
  "unhelpful",
  "unreliable",
  "horrendous",
  "not cooperative",
  "dismissive",
  "horrible hospitality",
  "biased",
  "dismissive",
  "cold",
  "indifferent",
  "delay",
  "unsafe",
  "unmanned",
  "inhospitable",
  "disgusting",
  "rude",
  "uncooperative",
  "ugly attitude",
  "unhelpful",
  "unpleasant",
  "stinky",
  "poor communication",
  "unkept",
  "urgent training",
  "noisy",
  "incompetent",
  "stinking",
  "unclean",
  "poor",
  "lazy",
];

const resultCommon = [
  1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0,
  1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0,
  1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
  1,
];

const finalData = [
  { keyword: "uninviting", department: "oops" },
  { keyword: "discomfort", department: "oops" },
  { keyword: "dirty", department: "oops" },
  { keyword: "poor", department: "oops" },
  { keyword: "unorganised", department: "oops" },
  { keyword: "horrible", department: "oops" },
  { keyword: "unhelpful", department: "oops" },
  { keyword: "slow", department: "oops" },
  { keyword: "inhospitable", department: "oops" },
  { keyword: "cold", department: "oops" },
  { keyword: "not flexible", department: "oops" },
  { keyword: "disrespectful", department: "oops" },
  { keyword: "unfriendly", department: "oops" },
  { keyword: "rude", department: "oops" },
  { keyword: "unwelcoming", department: "oops" },
  { keyword: "not professional", department: "oops" },
  { keyword: "unapproachable", department: "oops" },
  { keyword: "ignorant", department: "oops" },
  { keyword: "off putting", department: "oops" },
  { keyword: "dismissive", department: "oops" },
  { keyword: "unkept", department: "oops" },
  { keyword: "unclean", department: "oops" },
  { keyword: "unpleasant", department: "oops" },
  { keyword: "smelly", department: "oops" },
  { keyword: "stinky", department: "oops" },
  { keyword: "poor communication", department: "oops" },
  { keyword: "unsafe", department: "oops" },
  { keyword: "noisy", department: "oops" },
  { keyword: "unmanned", department: "oops" },
  { keyword: "empty", department: "oops" },
  { keyword: "nobody", department: "oops" },
  { keyword: "terrible", department: "oops" },
  { keyword: "uncooperative", department: "oops" },
  { keyword: "awful", department: "oops" },
  { keyword: "horrific", department: "oops" },
  { keyword: "horrendous", department: "oops" },
  { keyword: "inadequate", department: "oops" },
  { keyword: "gloomy", department: "oops" },
  { keyword: "dull", department: "oops" },
  { keyword: "lousy", department: "oops" },
  { keyword: "lazy", department: "oops" },
  { keyword: "refuse", department: "oops" },
  { keyword: "disgusting", department: "oops" },
  { keyword: "stink", department: "oops" },
  { keyword: "stench", department: "oops" },
  { keyword: "stinking", department: "oops" },
  { keyword: "smelling", department: "oops" },
  { keyword: "offensive", department: "oops" },
  { keyword: "reek", department: "oops" },
  { keyword: "horrible hospitality", department: "oops" },

  { keyword: "incompetent", department: "hr/oops" },
  { keyword: "unhelpful", department: "hr/oops" },
  { keyword: "negligent", department: "hr/oops" },
  { keyword: "unprofessional", department: "hr/oops" },
  { keyword: "inattentive", department: "hr/oops" },
  { keyword: "rude", department: "hr/oops" },
  { keyword: "indifferent", department: "hr/oops" },
  { keyword: "dismissive", department: "hr/oops" },
  { keyword: "inefficient", department: "hr/oops" },
  { keyword: "lazy", department: "hr/oops" },
  { keyword: "uncooperative", department: "hr/oops" },
  { keyword: "irresponsible", department: "hr/oops" },
  { keyword: "careless", department: "hr/oops" },
  { keyword: "unresponsive", department: "hr/oops" },
  { keyword: "disorganized", department: "hr/oops" },
  { keyword: "arrogant", department: "hr/oops" },
  { keyword: "dirty", department: "hr/oops" },
  { keyword: "impolite", department: "hr/oops" },
  { keyword: "unreliable", department: "hr/oops" },
  { keyword: "staff behavior", department: "hr/oops" },
  { keyword: "unsympathetic", department: "hr/oops" },
  { keyword: "offensive", department: "hr/oops" },
  { keyword: "ignoring", department: "hr/oops" },
  { keyword: "delay", department: "hr/oops" },
  { keyword: "not cooperative", department: "hr/oops" },
  { keyword: "horrible hospitality", department: "hr/oops" },
  { keyword: "ugly attitude", department: "hr/oops" },
  { keyword: "urgent training", department: "hr/oops" },
  { keyword: "biased", department: "hr/oops" },
];

// Example output
// console.log(finalData);

//shuffle data
const shuffledData = finalData.sort(() => 0.5 - Math.random());

// console.log(shuffledData);

const arrayOops: string[] = [
  "The restaurant had an uninviting atmosphere that made us reconsider our choice.",
  "From the moment we entered, the place felt cold and uninviting.",
  "I felt a sense of discomfort the entire time I was there.",
  "The seating was cramped, leading to considerable discomfort during my meal.",

  "The tables were dirty and hadn't been wiped down, which was off-putting.",
  "I was shocked at how dirty the floors were; it felt neglected.",

  "The service was poor, and it took forever to get our orders.",
  "I had high hopes, but the quality of the food was disappointingly poor.",

  "The event was completely unorganised, leading to a chaotic experience.",
  "I found the staff to be unorganised, which resulted in long wait times.",

  "I had a horrible experience with the customer service.",
  "The food was horrible, lacking flavor and presentation.",

  "The staff was unhelpful when I asked for assistance.",
  "I found the unhelpful attitude of the employees frustrating.",

  "The service was incredibly slow, and we waited too long for our drinks.",
  "I couldn't believe how slow the staff was to attend to our table.",

  "The staff's inhospitable demeanor made us feel unwelcome.",
  "It was a truly inhospitable environment, lacking any warmth or friendliness.",

  "The dining area was cold, making it uncomfortable to enjoy our meal.",
  "I was surprised at how cold it felt inside, despite the warm weather outside.",

  "The restaurant was not flexible with menu changes, which was disappointing.",
  "I found the staff to be not flexible when it came to accommodating dietary restrictions.",

  "The server was disrespectful when we pointed out an issue with our order.",
  "I couldn't believe the disrespectful tone taken by the staff.",

  "The staff were unfriendly and seemed disinterested in helping us.",
  "An unfriendly attitude from the employees made our visit less enjoyable.",

  "One of the waitstaff was incredibly rude when I asked for a different dish.",
  "I experienced rude service that really soured my mood.",

  "The atmosphere felt unwelcoming, with no one greeting us upon arrival.",
  "I found the overall vibe of the place to be unwelcoming and cold.",

  "The staff's behavior was not professional, lacking basic etiquette.",
  "It was clear that the service was not professional, which was disappointing.",

  "The manager seemed unapproachable, making it hard to voice our concerns.",
  "I found the staff to be unapproachable when I needed assistance.",

  "The employees were ignorant of their menu, which was frustrating.",
  "I was shocked by how ignorant the staff was about the specials.",

  "The overall cleanliness was off-putting and made us want to leave.",
  "I found the décor to be off-putting and not at all inviting.",

  "The waiter was dismissive when I asked for recommendations.",
  "I felt dismissed and undervalued as a customer during my visit.",

  "The restrooms were unkempt and needed serious attention.",
  "I noticed the outdoor area was unkempt and not well maintained.",

  "The tables were unclean, with crumbs left from previous diners.",
  "I was shocked by how unclean the facilities were.",

  "My overall experience was unpleasant, filled with issues.",
  "The food was unpleasant and didn’t taste fresh at all.",

  "The place had a smelly odor that made it hard to enjoy our meal.",
  "I couldn’t ignore the smelly environment; it was quite distracting.",

  "The stinky air made it uncomfortable to stay for long.",
  "I couldn't believe how stinky the kitchen area was.",

  "There was poor communication from the staff regarding our order.",
  "I experienced poor communication when trying to resolve an issue.",

  "I felt unsafe with the way things were managed around the restaurant.",
  "The environment felt unsafe, with several hazards in plain sight.",

  "The atmosphere was noisy, making it hard to hold a conversation.",
  "I found the place excessively noisy and chaotic.",

  "The reception area was unmanned when we arrived, which was frustrating.",
  "We were left waiting because the counter was unmanned for too long.",

  "The place was surprisingly empty, which made it feel eerie.",
  "I was taken aback by how empty the restaurant was on a weekend evening.",

  "There was nobody to help us when we walked in.",
  "I noticed nobody around to answer our questions about the menu.",

  "The food was terrible and did not meet our expectations.",
  "We had a terrible experience with the long wait times.",

  "The staff was uncooperative when we tried to change our reservation.",
  "I found the team to be uncooperative, making our visit difficult.",

  "The experience was awful, and I won’t be returning.",
  "I had an awful time with the service; it felt rushed and unkind.",

  "The state of the kitchen was horrific; I couldn’t believe my eyes.",
  "I had a horrific experience, from the service to the food quality.",

  "The wait time was horrendous, leaving us frustrated.",
  "I was appalled by the horrendous conditions of the dining area.",

  "The portion sizes were inadequate for the price we paid.",
  "I found the staff's response to be inadequate for the situation.",

  "The décor was gloomy and did not create an inviting atmosphere.",
  "It felt gloomy inside, which affected the overall experience.",

  "The menu options were dull and lacked creativity.",
  "I found the ambiance dull and uninspiring.",

  "The service was simply lousy, with inattentive staff.",
  "I had a lousy experience overall and wouldn't recommend it.",

  "The staff seemed lazy and uninterested in providing good service.",
  "I was disappointed by the lazy approach to customer care.",

  "The staff refused to accommodate our request for a different table.",
  "I was shocked when they refused to offer a refund for our meal.",

  "The food was disgusting, and I couldn't finish my meal.",
  "The restroom facilities were disgusting and in dire need of cleaning.",

  "There was a noticeable stink coming from the kitchen.",
  "I couldn't ignore the unpleasant stink lingering in the air.",

  "The stench of garbage was overwhelming as we entered.",
  "I was put off by the stench that permeated the dining area.",

  "The stinking odor made it difficult to enjoy my meal.",
  "There was a stinking smell that ruined the ambiance completely.",

  "The food was smelling off, which made me uneasy.",
  "I couldn't shake the feeling that something was smelling bad in the kitchen.",

  "The way the staff treated us was offensive and rude.",
  "I found the comments made by the staff to be offensive.",

  "The place reeked of old food and cleaning supplies.",
  "I was shocked at how much the place reeked of something foul.",

  "I experienced horrible hospitality, feeling like a nuisance rather than a guest.",
  "The horrible hospitality made it clear that they didn’t care about customer satisfaction.",
];

const arrayOopsResult: number[] = [
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
];

const arrayOopsHr: string[] = [
  "The staff was completely incompetent when it came to handling our order.",
  "I felt frustrated by the incompetent service that ruined our experience.",

  "The employees were unhelpful when I asked for basic information.",
  "I found the unhelpful attitude of the staff very disappointing.",

  "The negligent approach to cleanliness was alarming.",
  "I noticed several safety issues that seemed negligent on the part of management.",

  "The service was unprofessional, lacking any sense of courtesy.",
  "I was taken aback by the unprofessional behavior of the staff.",

  "The waiter was inattentive, making us wait far too long for service.",
  "I found the staff to be inattentive to our needs throughout the meal.",

  "One of the staff members was rude and dismissive when I raised a concern.",
  "I experienced rude service that left a bad taste in my mouth.",

  "The employees were indifferent to our complaints and requests.",
  "I was surprised by their indifferent attitude toward customer satisfaction.",

  "The manager's dismissive response to our feedback was unacceptable.",
  "I felt dismissed and unvalued during my entire visit.",

  "The service was inefficient, causing unnecessary delays.",
  "I was frustrated by the inefficient handling of our order.",

  "The staff seemed lazy and uninterested in providing quality service.",
  "I found the lazy approach to customer care quite disheartening.",

  "The team was uncooperative when we asked to make changes to our reservation.",
  "I encountered uncooperative staff who refused to address our concerns.",

  "The irresponsible handling of our complaints was shocking.",
  "I felt the staff was irresponsible in managing the dining area.",

  "The careless attitude of the employees affected the quality of our experience.",
  "I noticed several careless mistakes that were frustrating.",

  "The staff was unresponsive to our requests, making it a difficult visit.",
  "I felt ignored as the unresponsive staff failed to assist us.",

  "The restaurant was disorganized, leading to confusion and delays.",
  "I couldn't believe how disorganized the service was during our meal.",

  "The server had an arrogant attitude that made us uncomfortable.",
  "I was taken aback by the arrogant remarks made by the staff.",

  "The tables were dirty, which made the whole experience less enjoyable.",
  "I was shocked at how dirty the restroom facilities were.",

  "The staff was impolite when we inquired about the menu.",
  "I felt disrespected by the impolite demeanor of the waiter.",

  "The service was unreliable, with incorrect orders being common.",
  "I found the staff to be unreliable when it came to meeting our needs.",

  "The staff behavior was unprofessional and unwelcoming.",
  "I was appalled by the poor staff behavior throughout my visit.",

  "The staff was unsympathetic to our concerns about the food quality.",
  "I felt disappointed by the unsympathetic responses from the employees.",

  "Some of the comments made by the staff were offensive and inappropriate.",
  "I found the behavior of one employee to be offensive and uncalled for.",

  "The staff was busy ignoring our requests, which was frustrating.",
  "I felt like they were purposely ignoring our table throughout our visit.",

  "There was an excessive delay in receiving our food, which was unacceptable.",
  "The long delay made the entire experience less enjoyable.",

  "The team was not cooperative when we asked for assistance.",
  "I encountered several staff members who were not cooperative at all.",

  "The horrible hospitality made us feel like we were an inconvenience.",
  "I was disappointed by the horrible hospitality and lack of warmth.",

  "The server had an ugly attitude that ruined our dining experience.",
  "I couldn't believe the ugly attitude displayed by the staff.",

  "The level of service clearly indicated that urgent training was needed.",
  "I would suggest urgent training for the staff to improve their skills.",

  "I felt the service was biased, favoring certain customers over others.",
  "The biased treatment we received was disappointing and unfair.",
];

const arrayOopsHrResult: number[] = [
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1,
];

// Combine values and results into a single array of arrays
const combined: string[] = arrayOops.concat(arrayOopsHr);
const combinedResult = arrayOopsResult.concat(arrayOopsHrResult);

// console.log(combinedResult);

const shuffleArrays = (arr1: string[], arr2: number[]) => {
  const length = arr1.length;

  for (let i = length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));

    // Swap elements in arr1
    [arr1[i], arr1[j]] = [arr1[j], arr1[i]];

    // Swap elements in arr2
    [arr2[i], arr2[j]] = [arr2[j], arr2[i]];
  }
};

shuffleArrays(combined, combinedResult);

// console.log(JSON.stringify(combined));
// console.log(JSON.stringify(combinedResult));

export const swappedCombined = [
  "I found the staff to be unreliable when it came to meeting our needs.",
  "The food was smelling off, which made me uneasy.",
  "The atmosphere felt unwelcoming, with no one greeting us upon arrival.",
  "I experienced rude service that left a bad taste in my mouth.",
  "From the moment we entered, the place felt cold and uninviting.",
  "I was shocked at how much the place reeked of something foul.",
  "The staff was impolite when we inquired about the menu.",
  "The team was not cooperative when we asked for assistance.",
  "The tables were unclean, with crumbs left from previous diners.",
  "The service was poor, and it took forever to get our orders.",
  "The stinky air made it uncomfortable to stay for long.",
  "The server had an arrogant attitude that made us uncomfortable.",
  "It felt gloomy inside, which affected the overall experience.",
  "The restaurant was disorganized, leading to confusion and delays.",
  "The dining area was cold, making it uncomfortable to enjoy our meal.",
  "I felt like they were purposely ignoring our table throughout our visit.",
  "The tables were dirty and hadn't been wiped down, which was off-putting.",
  "I found the unhelpful attitude of the employees frustrating.",
  "There was an excessive delay in receiving our food, which was unacceptable.",
  "There was poor communication from the staff regarding our order.",
  "I couldn't believe how slow the staff was to attend to our table.",
  "I found the staff to be not flexible when it came to accommodating dietary restrictions.",
  "I found the place excessively noisy and chaotic.",
  "The place was surprisingly empty, which made it feel eerie.",
  "I felt frustrated by the incompetent service that ruined our experience.",
  "The restaurant was not flexible with menu changes, which was disappointing.",
  "The experience was awful, and I won’t be returning.",
  "The manager's dismissive response to our feedback was unacceptable.",
  "The employees were unhelpful when I asked for basic information.",
  "The manager seemed unapproachable, making it hard to voice our concerns.",
  "I encountered several staff members who were not cooperative at all.",
  "The tables were dirty, which made the whole experience less enjoyable.",
  "I had a horrible experience with the customer service.",
  "I was taken aback by how empty the restaurant was on a weekend evening.",
  "The food was terrible and did not meet our expectations.",
  "The food was unpleasant and didn’t taste fresh at all.",
  "My overall experience was unpleasant, filled with issues.",
  "The overall cleanliness was off-putting and made us want to leave.",
  "I had high hopes, but the quality of the food was disappointingly poor.",
  "The irresponsible handling of our complaints was shocking.",
  "The staff was completely incompetent when it came to handling our order.",
  "Some of the comments made by the staff were offensive and inappropriate.",
  "I couldn’t ignore the smelly environment; it was quite distracting.",
  "The reception area was unmanned when we arrived, which was frustrating.",
  "I found the décor to be off-putting and not at all inviting.",
  "The service was unprofessional, lacking any sense of courtesy.",
  "I found the staff to be inattentive to our needs throughout the meal.",
  "The state of the kitchen was horrific; I couldn’t believe my eyes.",
  "The restroom facilities were disgusting and in dire need of cleaning.",
  "I was taken aback by the unprofessional behavior of the staff.",
  "I would suggest urgent training for the staff to improve their skills.",
  "I found the staff to be unapproachable when I needed assistance.",
  "The seating was cramped, leading to considerable discomfort during my meal.",
  "The service was unreliable, with incorrect orders being common.",
  "I felt unsafe with the way things were managed around the restaurant.",
  "I found the unhelpful attitude of the staff very disappointing.",
  "The staff's inhospitable demeanor made us feel unwelcome.",
  "I found the comments made by the staff to be offensive.",
  "I found the lazy approach to customer care quite disheartening.",
  "The staff were unfriendly and seemed disinterested in helping us.",
  "The service was incredibly slow, and we waited too long for our drinks.",
  "The environment felt unsafe, with several hazards in plain sight.",
  "I couldn't believe how disorganized the service was during our meal.",
  "The employees were indifferent to our complaints and requests.",
  "The horrible hospitality made us feel like we were an inconvenience.",
  "I noticed several safety issues that seemed negligent on the part of management.",
  "The long delay made the entire experience less enjoyable.",
  "The level of service clearly indicated that urgent training was needed.",
  "I experienced poor communication when trying to resolve an issue.",
  "The staff was unresponsive to our requests, making it a difficult visit.",
  "I was disappointed by the horrible hospitality and lack of warmth.",
  "The negligent approach to cleanliness was alarming.",
  "I couldn't believe the ugly attitude displayed by the staff.",
  "I felt disappointed by the unsympathetic responses from the employees.",
  "The wait time was horrendous, leaving us frustrated.",
  "The menu options were dull and lacked creativity.",
  "The staff was busy ignoring our requests, which was frustrating.",
  "The food was disgusting, and I couldn't finish my meal.",
  "The way the staff treated us was offensive and rude.",
  "I experienced rude service that really soured my mood.",
  "I was disappointed by the lazy approach to customer care.",
  "I couldn't ignore the unpleasant stink lingering in the air.",
  "The place reeked of old food and cleaning supplies.",
  "I couldn't believe the disrespectful tone taken by the staff.",
  "The service was simply lousy, with inattentive staff.",
  "I was shocked by how ignorant the staff was about the specials.",
  "The team was uncooperative when we asked to make changes to our reservation.",
  "We had a terrible experience with the long wait times.",
  "The service was inefficient, causing unnecessary delays.",
  "The waiter was dismissive when I asked for recommendations.",
  "I had a lousy experience overall and wouldn't recommend it.",
  "I was appalled by the poor staff behavior throughout my visit.",
  "The server had an ugly attitude that ruined our dining experience.",
  "I was surprised by their indifferent attitude toward customer satisfaction.",
  "The portion sizes were inadequate for the price we paid.",
  "I found the ambiance dull and uninspiring.",
  "The staff was unhelpful when I asked for assistance.",
  "I couldn't believe how stinky the kitchen area was.",
  "I felt ignored as the unresponsive staff failed to assist us.",
  "I noticed the outdoor area was unkempt and not well maintained.",
  "I found the behavior of one employee to be offensive and uncalled for.",
  "The staff's behavior was not professional, lacking basic etiquette.",
  "There was a stinking smell that ruined the ambiance completely.",
  "An unfriendly attitude from the employees made our visit less enjoyable.",
  "I was shocked at how dirty the restroom facilities were.",
  "The event was completely unorganised, leading to a chaotic experience.",
  "The server was disrespectful when we pointed out an issue with our order.",
  "I felt a sense of discomfort the entire time I was there.",
  "I found the team to be uncooperative, making our visit difficult.",
  "We were left waiting because the counter was unmanned for too long.",
  "I encountered uncooperative staff who refused to address our concerns.",
  "I found the staff to be unorganised, which resulted in long wait times.",
  "I noticed nobody around to answer our questions about the menu.",
  "I felt dismissed and unvalued during my entire visit.",
  "I was taken aback by the arrogant remarks made by the staff.",
  "The restrooms were unkempt and needed serious attention.",
  "One of the staff members was rude and dismissive when I raised a concern.",
  "One of the waitstaff was incredibly rude when I asked for a different dish.",
  "I had an awful time with the service; it felt rushed and unkind.",
  "I was shocked at how dirty the floors were; it felt neglected.",
  "I noticed several careless mistakes that were frustrating.",
  "The stinking odor made it difficult to enjoy my meal.",
  "I was put off by the stench that permeated the dining area.",
  "I was surprised at how cold it felt inside, despite the warm weather outside.",
  "I was shocked when they refused to offer a refund for our meal.",
  "The restaurant had an uninviting atmosphere that made us reconsider our choice.",
  "The staff seemed lazy and uninterested in providing quality service.",
  "The staff behavior was unprofessional and unwelcoming.",
  "I experienced horrible hospitality, feeling like a nuisance rather than a guest.",
  "The staff was uncooperative when we tried to change our reservation.",
  "I felt disrespected by the impolite demeanor of the waiter.",
  "The staff seemed lazy and uninterested in providing good service.",
  "The waiter was inattentive, making us wait far too long for service.",
  "I was appalled by the horrendous conditions of the dining area.",
  "The décor was gloomy and did not create an inviting atmosphere.",
  "It was clear that the service was not professional, which was disappointing.",
  "The atmosphere was noisy, making it hard to hold a conversation.",
  "The staff refused to accommodate our request for a different table.",
  "The biased treatment we received was disappointing and unfair.",
  "The stench of garbage was overwhelming as we entered.",
  "There was nobody to help us when we walked in.",
  "The careless attitude of the employees affected the quality of our experience.",
  "I found the overall vibe of the place to be unwelcoming and cold.",
  "It was a truly inhospitable environment, lacking any warmth or friendliness.",
  "I was shocked by how unclean the facilities were.",
  "There was a noticeable stink coming from the kitchen.",
  "The food was horrible, lacking flavor and presentation.",
  "I was frustrated by the inefficient handling of our order.",
  "I couldn't shake the feeling that something was smelling bad in the kitchen.",
  "The place had a smelly odor that made it hard to enjoy our meal.",
  "The staff was unsympathetic to our concerns about the food quality.",
  "I felt dismissed and undervalued as a customer during my visit.",
  "I felt the staff was irresponsible in managing the dining area.",
  "The horrible hospitality made it clear that they didn’t care about customer satisfaction.",
  "The employees were ignorant of their menu, which was frustrating.",
  "I had a horrific experience, from the service to the food quality.",
  "I felt the service was biased, favoring certain customers over others.",
  "I found the staff's response to be inadequate for the situation.",
];
export const swappedCombinedResult = [
  1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
  0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0,
  0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
  1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
  1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
  1, 0,
];


console.log(swappedCombinedResult.at(swappedCombined.findIndex(review=> review === "There was a noticeable stink coming from the kitchen.")));



export const wordIndexCreated = {
  "i": 1,
  "found": 2,
  "the": 3,
  "staff": 4,
  "to": 5,
  "be": 6,
  "unreliable": 7,
  "when": 8,
  "it": 9,
  "came": 10,
  "meeting": 11,
  "our": 12,
  "needs.": 13,
  "food": 14,
  "was": 15,
  "smelling": 16,
  "off,": 17,
  "which": 18,
  "made": 19,
  "me": 20,
  "uneasy.": 21,
  "atmosphere": 22,
  "felt": 23,
  "unwelcoming,": 24,
  "with": 25,
  "no": 26,
  "one": 27,
  "greeting": 28,
  "us": 29,
  "upon": 30,
  "arrival.": 31,
  "experienced": 32,
  "rude": 33,
  "service": 34,
  "that": 35,
  "left": 36,
  "a": 37,
  "bad": 38,
  "taste": 39,
  "in": 40,
  "my": 41,
  "mouth.": 42,
  "from": 43,
  "moment": 44,
  "we": 45,
  "entered,": 46,
  "place": 47,
  "cold": 48,
  "and": 49,
  "uninviting.": 50,
  "shocked": 51,
  "at": 52,
  "how": 53,
  "much": 54,
  "reeked": 55,
  "of": 56,
  "something": 57,
  "foul.": 58,
  "impolite": 59,
  "inquired": 60,
  "about": 61,
  "menu.": 62,
  "team": 63,
  "not": 64,
  "cooperative": 65,
  "asked": 66,
  "for": 67,
  "assistance.": 68,
  "tables": 69,
  "were": 70,
  "unclean,": 71,
  "crumbs": 72,
  "previous": 73,
  "diners.": 74,
  "poor,": 75,
  "took": 76,
  "forever": 77,
  "get": 78,
  "orders.": 79,
  "stinky": 80,
  "air": 81,
  "uncomfortable": 82,
  "stay": 83,
  "long.": 84,
  "server": 85,
  "had": 86,
  "an": 87,
  "arrogant": 88,
  "attitude": 89,
  "uncomfortable.": 90,
  "gloomy": 91,
  "inside,": 92,
  "affected": 93,
  "overall": 94,
  "experience.": 95,
  "restaurant": 96,
  "disorganized,": 97,
  "leading": 98,
  "confusion": 99,
  "delays.": 100,
  "dining": 101,
  "area": 102,
  "cold,": 103,
  "making": 104,
  "enjoy": 105,
  "meal.": 106,
  "like": 107,
  "they": 108,
  "purposely": 109,
  "ignoring": 110,
  "table": 111,
  "throughout": 112,
  "visit.": 113,
  "dirty": 114,
  "hadn't": 115,
  "been": 116,
  "wiped": 117,
  "down,": 118,
  "off-putting.": 119,
  "unhelpful": 120,
  "employees": 121,
  "frustrating.": 122,
  "there": 123,
  "excessive": 124,
  "delay": 125,
  "receiving": 126,
  "food,": 127,
  "unacceptable.": 128,
  "poor": 129,
  "communication": 130,
  "regarding": 131,
  "order.": 132,
  "couldn't": 133,
  "believe": 134,
  "slow": 135,
  "attend": 136,
  "table.": 137,
  "flexible": 138,
  "accommodating": 139,
  "dietary": 140,
  "restrictions.": 141,
  "excessively": 142,
  "noisy": 143,
  "chaotic.": 144,
  "surprisingly": 145,
  "empty,": 146,
  "feel": 147,
  "eerie.": 148,
  "frustrated": 149,
  "by": 150,
  "incompetent": 151,
  "ruined": 152,
  "menu": 153,
  "changes,": 154,
  "disappointing.": 155,
  "experience": 156,
  "awful,": 157,
  "won’t": 158,
  "returning.": 159,
  "manager's": 160,
  "dismissive": 161,
  "response": 162,
  "feedback": 163,
  "basic": 164,
  "information.": 165,
  "manager": 166,
  "seemed": 167,
  "unapproachable,": 168,
  "hard": 169,
  "voice": 170,
  "concerns.": 171,
  "encountered": 172,
  "several": 173,
  "members": 174,
  "who": 175,
  "all.": 176,
  "dirty,": 177,
  "whole": 178,
  "less": 179,
  "enjoyable.": 180,
  "horrible": 181,
  "customer": 182,
  "service.": 183,
  "taken": 184,
  "aback": 185,
  "empty": 186,
  "on": 187,
  "weekend": 188,
  "evening.": 189,
  "terrible": 190,
  "did": 191,
  "meet": 192,
  "expectations.": 193,
  "unpleasant": 194,
  "didn’t": 195,
  "fresh": 196,
  "unpleasant,": 197,
  "filled": 198,
  "issues.": 199,
  "cleanliness": 200,
  "off-putting": 201,
  "want": 202,
  "leave.": 203,
  "high": 204,
  "hopes,": 205,
  "but": 206,
  "quality": 207,
  "disappointingly": 208,
  "poor.": 209,
  "irresponsible": 210,
  "handling": 211,
  "complaints": 212,
  "shocking.": 213,
  "completely": 214,
  "some": 215,
  "comments": 216,
  "offensive": 217,
  "inappropriate.": 218,
  "couldn’t": 219,
  "ignore": 220,
  "smelly": 221,
  "environment;": 222,
  "quite": 223,
  "distracting.": 224,
  "reception": 225,
  "unmanned": 226,
  "arrived,": 227,
  "décor": 228,
  "all": 229,
  "inviting.": 230,
  "unprofessional,": 231,
  "lacking": 232,
  "any": 233,
  "sense": 234,
  "courtesy.": 235,
  "inattentive": 236,
  "needs": 237,
  "state": 238,
  "kitchen": 239,
  "horrific;": 240,
  "eyes.": 241,
  "restroom": 242,
  "facilities": 243,
  "disgusting": 244,
  "dire": 245,
  "need": 246,
  "cleaning.": 247,
  "unprofessional": 248,
  "behavior": 249,
  "staff.": 250,
  "would": 251,
  "suggest": 252,
  "urgent": 253,
  "training": 254,
  "improve": 255,
  "their": 256,
  "skills.": 257,
  "unapproachable": 258,
  "needed": 259,
  "seating": 260,
  "cramped,": 261,
  "considerable": 262,
  "discomfort": 263,
  "during": 264,
  "unreliable,": 265,
  "incorrect": 266,
  "orders": 267,
  "being": 268,
  "common.": 269,
  "unsafe": 270,
  "way": 271,
  "things": 272,
  "managed": 273,
  "around": 274,
  "restaurant.": 275,
  "very": 276,
  "staff's": 277,
  "inhospitable": 278,
  "demeanor": 279,
  "unwelcome.": 280,
  "offensive.": 281,
  "lazy": 282,
  "approach": 283,
  "care": 284,
  "disheartening.": 285,
  "unfriendly": 286,
  "disinterested": 287,
  "helping": 288,
  "us.": 289,
  "incredibly": 290,
  "slow,": 291,
  "waited": 292,
  "too": 293,
  "long": 294,
  "drinks.": 295,
  "environment": 296,
  "unsafe,": 297,
  "hazards": 298,
  "plain": 299,
  "sight.": 300,
  "disorganized": 301,
  "indifferent": 302,
  "requests.": 303,
  "hospitality": 304,
  "inconvenience.": 305,
  "noticed": 306,
  "safety": 307,
  "issues": 308,
  "negligent": 309,
  "part": 310,
  "management.": 311,
  "entire": 312,
  "level": 313,
  "clearly": 314,
  "indicated": 315,
  "needed.": 316,
  "trying": 317,
  "resolve": 318,
  "issue.": 319,
  "unresponsive": 320,
  "requests,": 321,
  "difficult": 322,
  "disappointed": 323,
  "lack": 324,
  "warmth.": 325,
  "alarming.": 326,
  "ugly": 327,
  "displayed": 328,
  "unsympathetic": 329,
  "responses": 330,
  "employees.": 331,
  "wait": 332,
  "time": 333,
  "horrendous,": 334,
  "leaving": 335,
  "frustrated.": 336,
  "options": 337,
  "dull": 338,
  "lacked": 339,
  "creativity.": 340,
  "busy": 341,
  "disgusting,": 342,
  "finish": 343,
  "treated": 344,
  "rude.": 345,
  "really": 346,
  "soured": 347,
  "mood.": 348,
  "care.": 349,
  "stink": 350,
  "lingering": 351,
  "air.": 352,
  "old": 353,
  "cleaning": 354,
  "supplies.": 355,
  "disrespectful": 356,
  "tone": 357,
  "simply": 358,
  "lousy,": 359,
  "ignorant": 360,
  "specials.": 361,
  "uncooperative": 362,
  "make": 363,
  "changes": 364,
  "reservation.": 365,
  "times.": 366,
  "inefficient,": 367,
  "causing": 368,
  "unnecessary": 369,
  "waiter": 370,
  "recommendations.": 371,
  "lousy": 372,
  "wouldn't": 373,
  "recommend": 374,
  "it.": 375,
  "appalled": 376,
  "surprised": 377,
  "toward": 378,
  "satisfaction.": 379,
  "portion": 380,
  "sizes": 381,
  "inadequate": 382,
  "price": 383,
  "paid.": 384,
  "ambiance": 385,
  "uninspiring.": 386,
  "was.": 387,
  "ignored": 388,
  "as": 389,
  "failed": 390,
  "assist": 391,
  "outdoor": 392,
  "unkempt": 393,
  "well": 394,
  "maintained.": 395,
  "employee": 396,
  "uncalled": 397,
  "for.": 398,
  "professional,": 399,
  "etiquette.": 400,
  "stinking": 401,
  "smell": 402,
  "completely.": 403,
  "visit": 404,
  "were.": 405,
  "event": 406,
  "unorganised,": 407,
  "chaotic": 408,
  "pointed": 409,
  "out": 410,
  "issue": 411,
  "there.": 412,
  "uncooperative,": 413,
  "difficult.": 414,
  "waiting": 415,
  "because": 416,
  "counter": 417,
  "refused": 418,
  "address": 419,
  "resulted": 420,
  "nobody": 421,
  "answer": 422,
  "questions": 423,
  "dismissed": 424,
  "unvalued": 425,
  "remarks": 426,
  "restrooms": 427,
  "serious": 428,
  "attention.": 429,
  "raised": 430,
  "concern.": 431,
  "waitstaff": 432,
  "different": 433,
  "dish.": 434,
  "awful": 435,
  "service;": 436,
  "rushed": 437,
  "unkind.": 438,
  "floors": 439,
  "were;": 440,
  "neglected.": 441,
  "careless": 442,
  "mistakes": 443,
  "odor": 444,
  "put": 445,
  "off": 446,
  "stench": 447,
  "permeated": 448,
  "area.": 449,
  "despite": 450,
  "warm": 451,
  "weather": 452,
  "outside.": 453,
  "offer": 454,
  "refund": 455,
  "uninviting": 456,
  "reconsider": 457,
  "choice.": 458,
  "uninterested": 459,
  "providing": 460,
  "unwelcoming.": 461,
  "hospitality,": 462,
  "feeling": 463,
  "nuisance": 464,
  "rather": 465,
  "than": 466,
  "guest.": 467,
  "tried": 468,
  "change": 469,
  "disrespected": 470,
  "waiter.": 471,
  "good": 472,
  "inattentive,": 473,
  "far": 474,
  "horrendous": 475,
  "conditions": 476,
  "create": 477,
  "inviting": 478,
  "atmosphere.": 479,
  "clear": 480,
  "noisy,": 481,
  "hold": 482,
  "conversation.": 483,
  "accommodate": 484,
  "request": 485,
  "biased": 486,
  "treatment": 487,
  "received": 488,
  "disappointing": 489,
  "unfair.": 490,
  "garbage": 491,
  "overwhelming": 492,
  "entered.": 493,
  "help": 494,
  "walked": 495,
  "in.": 496,
  "vibe": 497,
  "unwelcoming": 498,
  "cold.": 499,
  "truly": 500,
  "environment,": 501,
  "warmth": 502,
  "or": 503,
  "friendliness.": 504,
  "unclean": 505,
  "noticeable": 506,
  "coming": 507,
  "kitchen.": 508,
  "horrible,": 509,
  "flavor": 510,
  "presentation.": 511,
  "inefficient": 512,
  "shake": 513,
  "concerns": 514,
  "quality.": 515,
  "undervalued": 516,
  "managing": 517,
  "menu,": 518,
  "horrific": 519,
  "experience,": 520,
  "biased,": 521,
  "favoring": 522,
  "certain": 523,
  "customers": 524,
  "over": 525,
  "others.": 526,
  "situation.": 527,
  "enjoyable": 528,
  "expectations": 529
}


// console.log(swappedCombinedResult.length)
// console.log(swappedCombined.length)